spring.application.name=hope_bank_app_middleware

dsumobapp.t24_base_url=https://10.2.1.6:9095/dsuwebservices/dsu/t24/transaction
dsumobapp.t24_token=GI3cGInKQBggBAtbSCDk73sgr/0Ur1aljPVYh2Nwr+OdWT4GQ4Jxl8V6z8NYJ5RgmkZQjVzPVgabLDjTIIDKF/wJk7R8cZ/dk6c5xT+QoQrYSTmNbVsqB4kRj2/1Zjw3KKI0uDZjlb3il2iUlKwew5C6bB7ZelopB4adsneEIiA966Kn1qoptFTgN8O7oxzg9DQtu6VbJPLtbZKkGcDCGPkGADyFZL5t
dsumobapp.t24_token_password=6X2eiuSsSMmtw3nS8Nfs5YklKlCX19Qm
dsumobapp.t24_sender_reference=dsu
dsumobapp.t24_service_source=JSON

dsumobapp.self_registration_txn_type=selfregistration
dsumobapp.mini_statement_txn_type=AccountMiniStatement
dsumobapp.account_information_txn_type=AccountInformation
dsumobapp.internal_transfer_txn_type=UssdInternalTransfer
dsumobapp.loan_balance_txn_type=LOAN_BALANCE
dsumobapp.account_balance_txn_type=BalanceEnquiry
dsumobapp.loan_repayment_txn_type=UssdLoanRepaymentAccount
dsumobapp.loan_repayment_momo_txn_type=UssdloanRepaymentMomo
dsumobapp.airtime_top_up_txn_type=UssdAirtimeToup
dsumobapp.transfer_to_other_bank_txn_type=UssdTransferToOtherBk
dsumobapp.transfer_bank_to_wallet_txn_type=UssdBankToWallet
dsumobapp.merchant_payment_txn_type=UssdMerchantPayment
dsumobapp.cardless_withdraw_txn_type=UssdCardlessWithdraw
dsumobapp.agent_withdraw_txn_type=UssdAgentWithdraw
dsumobapp.ussd_code=*123#
dsumobapp.sms_api_key=ed21e93c-352c-43fc-90d9-dff34b9188f2
dsumobapp.sms_base_url=https://10.2.1.6:9095/alertsender/v1/alert

# Existing properties...

# OpenAPI/Swagger Configuration
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
